# HEBI Robotics Kits - Arms

This folder contains examples for controlling arm-type configurations such as the 5-DoF and 6-DoF X-Series arm kits.

## Setup

### Load Libraries

These examples make use of a variety of HEBI libraries. In order to load the libraries correctly, please run `startup()` after starting up MATLAB.

### Setup Robot

In order to work with a robot arm, you need to establish communications, and create a matching kinematic model. If you are using a pre-configured link:http://docs.hebi.us/hardware.html#Kits[kit] with the default actuator types as well as default naming conventions, you can simply call `setupArm.m` as shown below.

[source,matlab]
----
% Load arm kit w/ default configuration
kit = '6dof';
[ group, kin, effortOffset, gravityVec ] = setupArm(kit)
----

The `kit` variable needs to match your system. Currently the following kits are supported:

:assembly: link:http://docs.hebi.us/resources/kits/assyInstructions
:kitimg: image:http://docs.hebi.us/resources/kits/images
:imgsize: width=300px

[width="100%",options="header",cols="1a,1a,2a,1a"]
|====================
| Kit Name | Part Number | Description and Info | Image

|`'6dof'`|A-2084-06|
6 - DoF Arm Kit +
{assembly}/6-DoF_Arm.pdf[Assembly Instructions]|
{kitimg}/6-DoF_Arm.PNG[{imgsize}]

|`'5dof'`|A-2084-05|
5 - DoF Arm Kit +
{assembly}/5-DoF_Arm.pdf[Assembly Instructions]|
{kitimg}/5-DoF_Arm.PNG[{imgsize}]

|`'4dof'`|A-2085-04|
4 - DoF Arm Kit +
{assembly}/4-DoF_Arm.pdf[Assembly Instructions]|
{kitimg}/4-DoF_Arm.PNG[{imgsize}]

|`'4dof-scara'`|A-2084-01|
4 - DoF SCARA Style Arm Kit +
{assembly}/4-DoF_SCARA-ish_Arm.pdf[Assembly Instructions]|
{kitimg}/4-DoF_SCARA.JPG[{imgsize}]

|====================

If you are using different actuator types or non-default configurations, you will need to modify the model to match your system. You can find tutorials on defining custom kinematic structures on the online link:http://docs.hebi.us/tools.html#kinematics[kinematics documentation]. The `setupArm.m` function should provide a good starting point.

### Set Gains

Pre-assembled kits should already come with good gains. However, depending on the example you may want to change the control strategy or simply test different gains.  You can do this via the Scope GUI or programmatically using the following code. More information on gain tuning can be found on the online link:http://docs.hebi.us/core_concepts.html#motor_control[motion control documentation].

[source,matlab]
----
% Change the control strategy of all modules in a group
desiredStrategy = 4; % change as needed
gains = GainStruct();
gains.controlStrategy = ones(1,group.getNumModules) * desiredStrategy;
group.send('gains', gains)
----

## Examples

At the top of each file is a `setup` section that may expose options for testing different behaviors.

Examples that are dependent on the number of degrees of freedom follow a naming convention with the kit name suffixed. Examples that are applicable to all kits do not have a suffix. They default to using the `4dof` kit, so please modify accordingly.

:code: link:./

[width="100%",options="header",cols="1a,3a,1a"]
|====================
| File | Topics | Recommended Control Strategy

|{code}/ex_kinematics_visualization.m[ex_kinematics_visualization]|
* passive visualization of robot configuration
|N/A

|{code}/ex_grav_comp.m[ex_grav_comp] +
(link:https://youtu.be/sli8Tq8FAQs[video])|
* gravity compensation for weight-less mode
|2/3/4 (identical for only torque)

|{code}/ex_teach_repeat.m[ex_teach_repeat]|
* record waypoints in gravity compensated mode
* replay waypoints with blocking trajectories
* logging and visualization
* keyboard input
|4

|{code}/ex_target_chase.m[ex_target_chase] +
(link:https://youtu.be/Ll20_6IsjnQ[video])|
* non-blocking trajectories
* continuous replaning to catch moving target
* inverse kinematics
* mouse input
|4 (dynamics comp on) or 3 (dynamics comp off)

|{code}/ex_target_chase_joystick.m[ex_target_chase_joystick] +
{code}/ex_target_chase_joystick_6dof.m[ex_target_chase_joystick_6dof] +
(link:https://youtu.be/ITrrnRo-UAI[video])|
* non-blocking trajectories
* continuous replaning to catch moving target
* inverse kinematics
* joystick input
|4 (dynamics comp on) or 3 (dynamics comp off)

|====================

## Experimenting with Gains

We recommend that you try running the samples with various gains and control strategies so that you can get a feel for the differences. The easiest way for editing gains is to save the current gains to disk, edit the file, and then load it. This also lets you use diff-tools for comparison.

[source,matlab]
----
fileName = './current-gains.xml';

% Save current gains
gains = group.getGains();
HebiUtils.saveGains(gains, fileName);

% Load gains from file
gains = HebiUtils.loadGains(fileName);
group.send('gains', gains);
----
