# HEBI Robotics Kits - Arms

This folder contains examples for controlling arm-type configurations such as the 5-DoF and 6-DoF X-Series arm kits.

*API Version: 1.0*

## Setup

### Load Libraries

These examples make use of a variety of HEBI libraries. In order to load the libraries correctly, please run `startup()` after starting up MATLAB.

Currently bundled APIs include

* hebi-matlab-1.0-rev1908 (link:http://docs.hebi.us[source])
* matlab-input-1.2 (link:https://github.com/HebiRobotics/MatlabInput/releases[source])

### Setup Robot

Open the `setupArm()` function and modify it to match your specific robot configuration. You can find tutorials on defining the kinematic structure on the online link:http://docs.hebi.us[documentation].

Depending on the example you may also want to change the control strategy or test different gains. You can do this via the Scope GUI or programmatically using the following code. More information on gain tuning can be found on the main documentation as well.

[source,matlab]
----
% Change the control strategy of all modules in a group
desiredStrategy = 4; % change as needed
gains = GainStruct();
gains.controlStrategy = ones(1,group.getNumModules) * desiredStrategy;
group.send('gains', gains)
----

## Examples

At the top of each file is a `setup` section that may expose options for testing different behaviors.

:code: link:./

[width="100%",options="header",cols="1a,3a,1a"]
|====================
| File | Topics | Recommended Control Strategy

|{code}/ex_kinematics_visualization.m[ex_kinematics_visualization]|
* passive visualization of robot configuration
|N/A

|{code}/ex_grav_comp.m[ex_grav_comp] +
(link:https://youtu.be/sli8Tq8FAQs[video])|
* gravity compensation for weight-less mode
|2/3/4 (identical for only torque)

|{code}/ex_teach_repeat.m[ex_teach_repeat]|
* record waypoints in gravity compensated mode
* replay waypoints with blocking trajectories
* logging and visualization
* keyboard input
|4

|{code}/ex_target_chase.m[ex_target_chase] +
(link:https://youtu.be/Ll20_6IsjnQ[video])|
* non-blocking trajectories
* continuous replaning to catch moving target
* inverse kinematics
* mouse input
|4 (dynamics comp on) or 3 (dynamics comp off)

|{code}/ex_target_chase_joystick.m[ex_target_chase_joystick] +
(link:https://youtu.be/Ll20_6IsjnQ[video])|
* non-blocking trajectories
* continuous replaning to catch moving target
* inverse kinematics
* joystick input
|4 (dynamics comp on) or 3 (dynamics comp off)

|====================

## Experimenting with Gains

We recommend that you try running the samples with various gains and control strategies so that you can get a feel for the differences. The easiest way for editing gains is to save the current gains to disk, edit the file, and then load it. This also lets you use diff-tools for comparison.

[source,matlab]
----
fileName = './current-gains.xml';

% Save current gains
gains = group.getGains();
HebiUtils.saveGains(gains, fileName);

% Load gains from file
gains = HebiUtils.loadGains(fileName);
group.send('gains', gains);
----
