# 6-DoF Arm
version: 1.0
families: ["Arm"]
names: ["J1_base", "J2_shoulder", "J3_elbow", "J4_wrist1", "J5_wrist2", "J6_wrist3"]
hrdf: "hrdf/A-2085-06.hrdf"

gains:
  default: "gains/A-2085-06.xml"

plugins:

  - type: GravityCompensationEffort
    name: gravComp
    enabled: false
    ramp_time: 0.5

  - type: DynamicsCompensationEffort
    name: dynamicsComp
    enabled: true
    ramp_time: 0.5

user_data:

  mobile_io_family: "Arm"
  mobile_io_name: "mobileIO"
  mobile_io_layout: "layouts/ex_gravity_compensation_toggle.json"