# X-Series Rosie with default omniwheel configuration
version: 1.0
families: ["Arm"]
names: ["J1_base", "J2_shoulder", "J3_elbow", "J4_wrist1", "J5_wrist2", "J6_wrist3"]
hrdf: "../hrdf/A-2240-06G.hrdf"

gains:
  default: "../gains/6-dof-arm-gains-rosie.xml"

plugins:

  - type: GravityCompensationEffort
    name: gravComp
    enabled: true
    ramp_time: 3

  - type: DynamicsCompensationEffort
    name: dynamicsComp
    enabled: true
    ramp_time: 3

user_data:
  gripper_family: "Arm"
  gripper_name: "gripperSpool"
  gripper_gains: "../gains/gripper-gains.xml"
  gripper_close_effort: -5
  gripper_open_effort: 1

  ikSeedPos: [0, 1, 2.5, 1.5, -1.5, 1]

  controller_family: "HEBI"
  controller_name: "mobileIO"
